package = "haskell-tools.nvim"
lua = "==5.1"

[source]
url = "https://github.com/mrcjkb/$(PACKAGE)/archive/refs/tags/v$(VERSION).zip"
dev = "git+https://github.com/mrcjkb/$(PACKAGE).git"

[description]
summary = "Supercharge your Haskell experience in Neovim!"
detailed = "This plugin automatically configures the haskell-language-server builtin LSP client and integrates with other Haskell tools. See the README's #features section for more info."
homepage = "https://github.com/mrcjkb/haskell-tools.nvim"
issues_url = "https://github.com/mrcjkb/haskell-tools.nvim/issues"
maintainer = "mrcjkb"
labels = [
  "dap",
  "debug-adapter-protocol",
  "haskell",
  "haskell-language-server",
  "language-server-protocol",
  "lsp",
  "neovim",
  "nvim",
  "plugin",
]
license = "GPL-2.0-only"

[build]
type = "builtin"
copy_directories = [
  "doc",
  "ftplugin",
]

[test]
type = "busted-nlua"

[test_dependencies]
nvim-dap = "0.10.0-1"
nvim-nio = "1.10.1-1"
"plenary.nvim" = "==0.1.4"
"telescope.nvim" = "==0.2.2"
"toggleterm.nvim" = "==2.13.1"
