name: Feature request
description: Request an enhancement for haskell-tools.nvim
labels: [enhancement]
body:

  - type: markdown
    attributes:
      value: |
        Before requesting: search [existing issues](https://github.com/MrcJkb/haskell-tools.nvim/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

  - type: textarea
    attributes:
      label: "Feature description"
    validations:
      required: true
