name: Question
description: Ask a question about haskell-tools.nvim
labels: [question]
body:

  - type: markdown
    attributes:
      value: |
        Before asking: search [existing issues](https://github.com/MrcJkb/haskell-tools.nvim/issues?q=is%3Aopen+is%3Aissue+label%3Aquestion).

  - type: textarea
    attributes:
      label: "Question"
    validations:
      required: true
