local ht = require('haskell-tools')
local stub = require('luassert.stub')
describe('Can require haskell-tools with default configs.', function()
  local notify_once = stub(vim, 'notify_once')
  local notify = stub(vim, 'notify')
  it('Public API is available after setup.', function()
    assert(ht.lsp ~= nil)
    assert(ht.hoogle ~= nil)
    assert(ht.repl ~= nil)
    assert(ht.project ~= nil)
    assert(ht.tags ~= nil)
  end)
  it('No notifications at startup.', function()
    assert.stub(notify_once).called_at_most(0)
    assert.stub(notify).called_at_most(0)
  end)
end)
