---
name: "Push to LuaRocks"
on:
  push:
    tags:
      - "*"
  release:
    types:
      - created
  pull_request:

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get Version
        run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          detailed_description: |
            This plugin automatically configures the haskell-language-server builtin LSP client
            and integrates with other Haskell tools. See the README's #features section
            for more info.
