name: "Release"
on:
  push:
    tags:
      - "*"
  pull_request:

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fail if changelog entry does not exist
        if: startsWith(github.ref, 'refs/tags/v')
        run: grep -q "${{ github.ref_name }}" CHANGELOG.md
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          dependencies: |
            plenary.nvim
          detailed_description: |
            This plugin automatically configures the haskell-language-server builtin LSP client
            and integrates with other Haskell tools. See the README's #features section
            for more info.
      - name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          allowUpdates: true

